[package]
name = "freight-paths"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
data = { path = "../../freight-data" }
home = "0.3"
structopt = "0.2.1"
serde_json = "1.0"
