[package]
name = "freight-configure"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
data = { path = "../../freight-data" }
failure = "0.1"
structopt = "0.2.1"
serde_json = "1.0"
